### PR TITLE
Add kong service and check definitions as config files

### PR DESCRIPTION
**Pull request by anonymouse64**
When coupled with https://github.com/edgexfoundry/docker-edgex-consul/pull/2, this will enable using the dependency checks put in the `docker-edgex-consul` container to successfully order the kong-db, kong-migration and kong containers in the security docker-compose.

In order to test this, you will need to take a look at the PR in developer-scripts: edgexfoundry/developer-scripts#147

### CODE REVIEW

**Comment by bnevis-i** [comment]
The auto check is failing on 
```
15:21:03 Step 18/20 : COPY static-services-config.json /consul/config
15:21:03 COPY failed: stat /var/lib/docker/tmp/docker-builder429323765/static-services-config.json: no such file or directory
15:21:03 Build step 'Execute shell' marked build as failure
```

which I find curious given you replaced that COPY line entirely.

**Comment by bnevis-i** [comment]
recheck

**Comment by anonymouse64** [comment]
Full testing information is available in the developer-scripts PR here: https://github.com/edgexfoundry/developer-scripts/pull/147

That PR's testing information should be used to test this PR as well

**Comment by anonymouse64** [comment]
This has been rebased with the version number change, so it will properly build for version 1.1 for Fuji now

**Comment by anonymouse64** [comment]
Ah the failing container here is the arm64 dockerfile... raises an interesting question why we have an arm64 dockerfile when this entire container is just static config files :thinking:

**Comment by bnevis-i** [comment]
> Ah the failing container here is the arm64 dockerfile... raises an interesting question why we have an arm64 dockerfile when this entire container is just static config files 🤔

Probably because you can probably only build for one platform at a time and docker needs an image that matches the target architecture.

**Comment by bnevis-i** [comment]
This PR might be an opportune time to fix #6 as well.

**Comment by anonymouse64** [comment]
@bnevis-i while I am in general in favor of fixing that, I'd rather get this PR in ASAP because I have 2 more after this for the security services themselves and I'd prefer to minimize any potential breakage by just adding things and not changing them per se...

I will look into making this container simpler while working on the other things I am doing because it's convenient to test such things, but I don't anticipate being able to get reviews enough to fix this next week.

**Comment by bnevis-i** [comment]
> I will look into making this container simpler while working on the other things I am doing because it's convenient to test such things, but I don't anticipate being able to get reviews enough to fix this next week.

Note I am not a committer in this repo and thus cannot give you what you seek.

**Pull request merged**
